import {
  Activity,
  AlertCircle,
  Apple,
  Baby,
  Bone,
  Brain,
  Briefcase,
  Droplets,
  Dumbbell,
  Ear,
  Eye,
  FlaskConical,
  Heart,
  HeartPulse,
  Home,
  Leaf,
  type LucideIcon,
  Microscope,
  Pill,
  Scale,
  Scan,
  Scissors,
  Search,
  Shield,
  Sparkles,
  Stethoscope,
  Sun,
  Syringe,
  Users,
  Wind,
  Zap,
} from "lucide-react";

export enum MedicalSpecialty {
  ALERGOLOGIA = "Alergologia",
  ANESTESIOLOGIA = "Anestesiologia",
  ANGIOLOGIA = "Angiologia",
  CANCEROLOGIA = "Cancerologia",
  CARDIOLOGIA = "Cardiologia",
  CIRURGIA_CARDIOVASCULAR = "Cirurgia Cardiovascular",
  CIRURGIA_CABECA_PESCOCO = "Cirurgia de Cabeça e Pescoço",
  CIRURGIA_DIGESTIVA = "Cirurgia do Aparelho Digestivo",
  CIRURGIA_GERAL = "Cirurgia Geral",
  CIRURGIA_PEDIATRICA = "Cirurgia Pediátrica",
  CIRURGIA_PLASTICA = "Cirurgia Plástica",
  CIRURGIA_TORACICA = "Cirurgia Torácica",
  CIRURGIA_VASCULAR = "Cirurgia Vascular",
  CLINICA_MEDICA = "Clínica Médica",
  DERMATOLOGIA = "Dermatologia",
  ENDOCRINOLOGIA = "Endocrinologia e Metabologia",
  ENDOSCOPIA = "Endoscopia",
  GASTROENTEROLOGIA = "Gastroenterologia",
  GERIATRIA = "Geriatria",
  GINECOLOGIA_OBSTETRICIA = "Ginecologia e Obstetrícia",
  HEMATOLOGIA = "Hematologia e Hemoterapia",
  HEPATOLOGIA = "Hepatologia",
  HOMEOPATIA = "Homeopatia",
  INFECTOLOGIA = "Infectologia",
  MASTOLOGIA = "Mastologia",
  MEDICINA_DE_EMERGENCIA = "Medicina de Emergência",
  MEDICINA_DO_ESPORTO = "Medicina do Esporte",
  MEDICINA_DO_TRABALHO = "Medicina do Trabalho",
  MEDICINA_DE_FAMILIA = "Medicina de Família e Comunidade",
  MEDICINA_FISICA_REABILITACAO = "Medicina Física e Reabilitação",
  MEDICINA_INTENSIVA = "Medicina Intensiva",
  MEDICINA_LEGAL = "Medicina Legal e Perícia Médica",
  NEFROLOGIA = "Nefrologia",
  NEUROCIRURGIA = "Neurocirurgia",
  NEUROLOGIA = "Neurologia",
  NUTROLOGIA = "Nutrologia",
  OFTALMOLOGIA = "Oftalmologia",
  ONCOLOGIA_CLINICA = "Oncologia Clínica",
  ORTOPEDIA_TRAUMATOLOGIA = "Ortopedia e Traumatologia",
  OTORRINOLARINGOLOGIA = "Otorrinolaringologia",
  PATOLOGIA = "Patologia",
  PATOLOGIA_CLINICA = "Patologia Clínica/Medicina Laboratorial",
  PEDIATRIA = "Pediatria",
  PNEUMOLOGIA = "Pneumologia",
  PSIQUIATRIA = "Psiquiatria",
  RADIOLOGIA = "Radiologia e Diagnóstico por Imagem",
  RADIOTERAPIA = "Radioterapia",
  REUMATOLOGIA = "Reumatologia",
  UROLOGIA = "Urologia",
}

export const medicalSpecialtyIcons: Record<MedicalSpecialty, LucideIcon> = {
  [MedicalSpecialty.ALERGOLOGIA]: Wind,
  [MedicalSpecialty.ANESTESIOLOGIA]: Syringe,
  [MedicalSpecialty.ANGIOLOGIA]: Activity,
  [MedicalSpecialty.CANCEROLOGIA]: Microscope,
  [MedicalSpecialty.CARDIOLOGIA]: Heart,
  [MedicalSpecialty.CIRURGIA_CARDIOVASCULAR]: HeartPulse,
  [MedicalSpecialty.CIRURGIA_CABECA_PESCOCO]: Scissors,
  [MedicalSpecialty.CIRURGIA_DIGESTIVA]: Scissors,
  [MedicalSpecialty.CIRURGIA_GERAL]: Scissors,
  [MedicalSpecialty.CIRURGIA_PEDIATRICA]: Baby,
  [MedicalSpecialty.CIRURGIA_PLASTICA]: Sparkles,
  [MedicalSpecialty.CIRURGIA_TORACICA]: Scissors,
  [MedicalSpecialty.CIRURGIA_VASCULAR]: Activity,
  [MedicalSpecialty.CLINICA_MEDICA]: Stethoscope,
  [MedicalSpecialty.DERMATOLOGIA]: Sun,
  [MedicalSpecialty.ENDOCRINOLOGIA]: Zap,
  [MedicalSpecialty.ENDOSCOPIA]: Search,
  [MedicalSpecialty.GASTROENTEROLOGIA]: Pill,
  [MedicalSpecialty.GERIATRIA]: Users,
  [MedicalSpecialty.GINECOLOGIA_OBSTETRICIA]: Baby,
  [MedicalSpecialty.HEMATOLOGIA]: Droplets,
  [MedicalSpecialty.HEPATOLOGIA]: Activity,
  [MedicalSpecialty.HOMEOPATIA]: Leaf,
  [MedicalSpecialty.INFECTOLOGIA]: Shield,
  [MedicalSpecialty.MASTOLOGIA]: Activity,
  [MedicalSpecialty.MEDICINA_DE_EMERGENCIA]: AlertCircle,
  [MedicalSpecialty.MEDICINA_DO_ESPORTO]: Dumbbell,
  [MedicalSpecialty.MEDICINA_DO_TRABALHO]: Briefcase,
  [MedicalSpecialty.MEDICINA_DE_FAMILIA]: Home,
  [MedicalSpecialty.MEDICINA_FISICA_REABILITACAO]: Activity,
  [MedicalSpecialty.MEDICINA_INTENSIVA]: AlertCircle,
  [MedicalSpecialty.MEDICINA_LEGAL]: Scale,
  [MedicalSpecialty.NEFROLOGIA]: Droplets,
  [MedicalSpecialty.NEUROCIRURGIA]: Brain,
  [MedicalSpecialty.NEUROLOGIA]: Brain,
  [MedicalSpecialty.NUTROLOGIA]: Apple,
  [MedicalSpecialty.OFTALMOLOGIA]: Eye,
  [MedicalSpecialty.ONCOLOGIA_CLINICA]: Microscope,
  [MedicalSpecialty.ORTOPEDIA_TRAUMATOLOGIA]: Bone,
  [MedicalSpecialty.OTORRINOLARINGOLOGIA]: Ear,
  [MedicalSpecialty.PATOLOGIA]: Microscope,
  [MedicalSpecialty.PATOLOGIA_CLINICA]: FlaskConical,
  [MedicalSpecialty.PEDIATRIA]: Baby,
  [MedicalSpecialty.PNEUMOLOGIA]: Wind,
  [MedicalSpecialty.PSIQUIATRIA]: Brain,
  [MedicalSpecialty.RADIOLOGIA]: Scan,
  [MedicalSpecialty.RADIOTERAPIA]: Zap,
  [MedicalSpecialty.REUMATOLOGIA]: Bone,
  [MedicalSpecialty.UROLOGIA]: Droplets,
};

export const medicalSpecialties = Object.entries(MedicalSpecialty).map(
  ([key, value]) => ({
    value: MedicalSpecialty[key as keyof typeof MedicalSpecialty],
    label: value,
    icon: medicalSpecialtyIcons[
      MedicalSpecialty[key as keyof typeof MedicalSpecialty]
    ],
  }),
);
